CREATE DATABASE DE01
USE DE01

--CAU 1:
CREATE TABLE LOAIKHSAN(
 MALKS CHAR(5) PRIMARY KEY, //kilo
 TENLKS VARCHAR(50),
 PHANLOAI VARCHAR(30)
)

CREATE TABLE KHOANGSAN(
 MAKS CHAR(5) PRIMARY KEY,
 TENKS VARCHAR(50),
 MALKS CHAR(5),
 TRANGTHAI VARCHAR(5)
)

CREATE TABLE CONGTY(
 MACTY CHAR(5) PRIMARY KEY,
 TENCTY CHAR(50),
 DIACHI CHAR(100),
 NGAYTL SMALLDATETIME
)

CREATE TABLE MOKS(
 MAMKS CHAR(5) PRIMARY KEY,
 TENMO VARCHAR(40),
 MAKS CHAR(5),
 NGPHATHIEN SMALLDATETIME,
 TINH VARCHAR(20)
)

CREATE TABLE KHAITHAC(
 MAMKS CHAR(5),
 MACTY CHAR(5),
 NGCP SMALLDATETIME,
 NGHH SMALLDATETIME,
 PRIMARY KEY (MAMKS, MACTY, NGCP)
)

ALTER TABLE KHOANGSAN ADD FOREIGN KEY (MALKS) REFERENCES LOAIKHSAN(MALKS)
ALTER TABLE MOKS ADD FOREIGN KEY (MAKS) REFERENCES KHOANGSAN(MAKS)
ALTER TABLE KHAITHAC ADD FOREIGN KEY (MAMKS) REFERENCES MOKS(MAMKS),
                         FOREIGN KEY (MACTY) REFERENCES CONGTY(MACTY)
--CAU 2:
--A/
ALTER TABLE KHOANGSAN ADD CHECK( TRANGTHAI IN ( 'RAN', 'LONG', 'KHI') )

--B/
CREATE TRIGGER TR_1 ON KHAITHAC
FOR INSERT, UPDATE
AS
BEGIN
 IF EXISTS( SELECT * FROM INSERTED I, CONGTY CT WHERE I.MACTY=CT.MACTY AND I.NGCP <= CT.NGAYTL )
	  BEGIN 
		   PRINT 'NGCP PHAI LON HON NGAYTL'
		   ROLLBACK TRAN 
	  END
 ELSE
	  BEGIN
		   PRINT 'THANH CONG'
	  END
END


CREATE TRIGGER TR_2 ON CONGTY
FOR UPDATE
AS
BEGIN
 IF EXISTS( SELECT * FROM INSERTED I, KHAITHAC KT WHERE I.MACTY=KT.MACTY AND KT.NGCP <= I.NGAYTL )
	  BEGIN 
		   PRINT 'NGCP PHAI LON HON NGAYTL'
		   ROLLBACK TRAN 
	  END
 ELSE
      BEGIN
		   PRINT 'THANH CONG'
	  END
END

--CAU 3:
--A/
SELECT MAKS, TENKS
FROM KHOANGSAN
WHERE TRANGTHAI='RAN'
ORDER BY MAKS DESC

--B/
SELECT KS.MAKS, KS.TENKS
FROM LOAIKHSAN LKS, KHOANGSAN KS
WHERE LKS.MALKS=KS.MALKS AND LKS.PHANLOAI='KHOANG SAN NANG LUONG'

--C/
SELECT MOKS.MAMKS, MOKS.TENMO, CT.TENCTY
FROM ( MOKS JOIN KHAITHAC KT ON MOKS.MAMKS=KT.MAMKS ) LEFT JOIN CONGTY CT ON CT.MACTY=KT.MACTY

--D/
SELECT CT.MACTY
FROM CONGTY CT 
WHERE NOT EXISTS
( SELECT * 
  FROM MOKS 
  WHERE MOKS.TINH='QUANG NINH' AND NOT EXISTS
	( SELECT * 
	  FROM KHAITHAC KT
	  WHERE KT.MACTY=CT.MACTY AND KT.MAMKS=MOKS.MAMKS
	)
)

--E/
SELECT CT.MACTY, COUNT(MOKS.MAMKS) AS 'SO LUONG MO KHOANG SAN'
FROM CONGTY CT, MOKS, KHAITHAC KT
WHERE CT.MACTY=KT.MACTY AND MOKS.MAMKS=KT.MAMKS AND YEAR(KT.NGCP)=2022
GROUP BY CT.MACTY

--F/
SELECT CT.MACTY, CT.TENCTY
FROM CONGTY CT, MOKS, KHAITHAC KT
WHERE CT.MACTY=KT.MACTY AND MOKS.MAMKS=KT.MAMKS AND YEAR(KT.NGCP)=2022 AND MOKS.TINH='QUANG NINH'
INTERSECT
SELECT CT.MACTY, CT.TENCTY
FROM CONGTY CT, MOKS, KHAITHAC KT
WHERE CT.MACTY=KT.MACTY AND MOKS.MAMKS=KT.MAMKS AND YEAR(KT.NGCP)=2022 AND MOKS.TINH='BAC CAN'
    
